language: python
cache: pip
sudo: required
distro: trusty
notifications:
  irc:
    channels:
    - chat.freenode.net#pycket
    use_notice: false
env:
  global:
  - PATH=./racket/bin:$PATH
  - PLTHOME=.
  matrix:
  - TEST_TYPE=old_tests
  - TEST_TYPE=new_tests_without_expander_linklet
  - TEST_TYPE=new_tests_using_expander_linklet
  - PYPY_DONT_RUN_SUBPROCESS=1 TEST_TYPE=translate
  - TEST_TYPE=translate_nojit_and_racket_tests
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=coverage TEST_TYPE=translate_nojit_and_racket_tests
before_install: travis_wait ./travis.sh prepare
install: ./travis.sh install
script: travis_wait ./travis.sh test $TEST_TYPE
