language: python
cache: apt
sudo: true
env:
  global:
  - PATH=./racket/bin:$PATH
  matrix:
  - TEST_TYPE=tests
  - TEST_TYPE=test_expander
  - PYPY_DONT_RUN_SUBPROCESS=1 TEST_TYPE=translate
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=coverage TEST_TYPE=translate_nojit_and_racket_tests
before_install: travis_wait ./travis.sh prepare
install: ./travis.sh install
script: travis_wait ./travis.sh test $TEST_TYPE
