language: python
cache: pip
sudo: required
dist: trusty
notifications:
  irc:
    channels:
    - chat.freenode.net#pycket
    use_notice: false
env:
  global:
  - PATH=./racket/bin:$PATH
  - PLTHOME=.
  matrix:
  - TEST_TYPE=old_tests
  - TEST_TYPE=new_tests_without_expander_linklet
  - TEST_TYPE=new_tests_using_expander_linklet
  - PYPY_DONT_RUN_SUBPROCESS=1 TEST_TYPE=translate
  - TEST_TYPE=translate_nojit_and_racket_tests
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=new_tests_without_expander_linklet
  - env: TEST_TYPE=new_tests_using_expander_linklet
before_install:
  - while sleep 9m; do printf "\n=====[ $SECONDS seconds still running ]=====\n"; done &
  -  ./travis.sh prepare
install:
  - while sleep 9m; do printf "\n=====[ $SECONDS seconds still running ]=====\n"; done &
  - ./travis.sh install
script:
  - while sleep 9m; do printf "\n=====[ $SECONDS seconds still running ]=====\n"; done &
  - ./travis.sh test $TEST_TYPE
