language: python
cache: pip
sudo: required
dist: trusty
env:
  global:
  - PATH=./racket/bin:$PATH
  - PLTHOME=.
  matrix:
  - TEST_TYPE=tests
  - PYPY_DONT_RUN_SUBPROCESS=1 TEST_TYPE=translate
  - TEST_TYPE=translate_nojit_and_racket_tests
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=coverage TEST_TYPE=translate_nojit_and_racket_tests
before_install: ./travis.sh prepare
install: ./travis.sh install
script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ./travis.sh test $TEST_TYPE
